version: '3.5'
services:
  neo4j:
    image: neo4j:5-community
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
    environment:
      NEO4J_AUTH: neo4j/password123